version: '3'
services:
  ddb:
    build:
      context: .
      dockerfile: Dockerfile.dolphindb
    image: ddb:findataflow
    volumes:
      - /data/dataset/ddb/server/local8848:/opt/ddb/server/local8848
    ports:
        - 8868:8848
    container_name: ddb-findataflow
    restart: always
    networks:
      - backend

networks: 
  backend:
    driver: bridge
